sudo: required
services:
  - docker
language: python
python:
  - "3.6"
cache: pip
install:
  - pip install invoke
script:
  - cd src/python/
  - invoke testDocker
deploy:
  provider: pypi
  username: PYPI_USERNAME
  password: PYPI_PASSWORD
